# This is a basic workflow to help you get started with Actions

name: GH Pages

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm 
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-:  

      - run: npm ci
      - run: npm run lint
      - run: npm run build

      - name: Deploy
        run: |
          echo ${{ github.actor }}
          echo ${{ github.repository_owner }}
          cd dist
          git init
          git checkout -b gh-pages
          git add .
          git config user.email "${{ github.repository_owner }}@@users.noreply.github.com"
          git config user.name "Github Action"
          git commit -m "Update GH Pages"
          git remote add origin https://${{ secrets.REPO_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push -f -u origin gh-pages
